[local]
localhost

[mongodb]
localhost

[catalogue]
localhost

[redis]
localhost

[user]
localhost

[cart]
localhost

[mysql]
localhost

[shipping]
shipping-dev.anilbeeraka.online

[rabbitmq]
localhost

[payment]
payment-dev.anilbeeraka.online

[frontend]
frontend-dev.anilbeeraka.online


